spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/[seu banco]?useTimeZone=true&serverTimeZone=UTC&useLegacyDate
    username: postgres
    password: "seu password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate_format_sql: true

  Logging:
    level:
      org:
        hibernate:
          type: trace
